/**
 * alphaGrid S9 — markdown report formatter for the AKEUSDT backtest (M2 deliverable).
 * Pure function of the driver report (BACKTEST_AKEUSDT.md is generated, never edited).
 */
import type { AlphaGridBacktestReport } from "./backtest-driver.js";

function fmt(n: number, digits = 2): string {
  return n.toFixed(digits);
}

export function formatBacktestMarkdown(report: AlphaGridBacktestReport): string {
  const s = report.settings;
  const lines: string[] = [];
  lines.push(`# alphaGrid backtest — ${report.symbol} 1h (M2)`);
  lines.push(``);
  lines.push(`Generated by \`packages/backtesting/src/alpha-grid/\` (driver + MemoryExchange simulation).`);
  lines.push(`Window: ${report.windowStart} → ${report.windowEnd} (${report.candleCount} hourly candles).`);
  lines.push(`Data: Binance USD-M futures public klines (\`fapi.binance.com/fapi/v1/klines\`),`);
  lines.push(`fetched via \`scripts/fetch-klines.mjs\` into gitignored \`klines/AKEUSDT-1h.json\`.`);
  lines.push(``);
  lines.push(`## Configuration (exact M2 settings + sized volume/capital)`);
  lines.push(``);
  lines.push(`| Setting | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| symbol | ${report.symbol} |`);
  lines.push(`| direction | ${s.direction} |`);
  lines.push(`| gridMode / atrTimeframe | ${s.gridMode} / ${s.atrTimeframe} |`);
  lines.push(`| nLevels | ${s.nLevels} |`);
  lines.push(`| atrMultiplier | ${s.atrMultiplier} |`);
  lines.push(`| volumePerLevel | ${s.volumePerLevel} (base asset) |`);
  lines.push(`| tpPct / stopLossPct | ${s.tpPct} / ${s.stopLossPct} |`);
  lines.push(`| leverage | ${s.leverage} |`);
  lines.push(`| useTrailing / useTakeProfit / useStopLoss / useExchangeStopOrder | ${s.useTrailing} / ${s.useTakeProfit} / ${s.useStopLoss} / ${s.useExchangeStopOrder} |`);
  lines.push(`| capital (allocated) | $${fmt(report.capital, 0)} |`);
  lines.push(`| commission maker/taker | 2 / 5 bps (Binance VIP0) |`);
  lines.push(`| taker slippage | 2 bps adverse |`);
  lines.push(``);
  lines.push(`## Results (honesty metrics — no cherry-picking)`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Total return | ${fmt(report.totalReturnPct)}% ($${fmt(report.finalEquity)} on $${fmt(report.capital, 0)}) |`);
  lines.push(`| Max drawdown | ${fmt(report.maxDrawdownPct)}% |`);
  lines.push(`| Win rate | ${fmt(report.winRate * 100)}% (${report.cycles.filter((c) => c.win).length}/${report.closedCycles} closed cycles net-positive) |`);
  lines.push(`| Closed cycles | ${report.closedCycles} (TP ${report.tpCycles}, stops ${report.stopOuts.length}, netted ${report.cycles.filter((c) => c.kind === "netted").length}) |`);
  lines.push(`| Stop-outs | ${report.stopOuts.length} (${report.stopOuts.filter((o) => o.kind === "exchange-hit").length} exchange-hit, ${report.stopOuts.filter((o) => o.kind === "supervisor").length} supervisor) |`);
  lines.push(`| Fees paid | $${fmt(report.totalFees, 4)} |`);
  lines.push(`| Liquidations | ${report.liquidations} (reported with context below — ruin is a finding, never hidden) |`);
  lines.push(`| Max margin used | $${fmt(report.maxMarginUsed)} |`);
  lines.push(``);
  lines.push(`## Stop-outs (unrealized ROI at trigger — every one ≈ −${s.stopLossPct}%)`);
  lines.push(``);
  if (report.stopOuts.length === 0) {
    lines.push(`None.`);
  } else {
    lines.push(`| # | Candle index | Time (UTC) | Layer | Unrealized ROI | Realized net |`);
    lines.push(`|---|---|---|---|---|---|`);
    report.stopOuts.forEach((o, i) => {
      lines.push(
        `| ${i + 1} | ${o.index} | ${new Date(o.timestamp).toISOString()} | ${o.kind} | ${fmt(o.roiAtTriggerPct)}% | $${fmt(o.realizedNet)} |`,
      );
    });
  }
  lines.push(``);
  lines.push(`## Methodology notes`);
  lines.push(``);
  lines.push(`- Same strategy code as live (local fills + mark price; no \`ccxt\` in logic).`);
  lines.push(`- Simulated fills: limit/stop orders match on candle low/high range crossing (wicks trigger);`);
  lines.push(`  stop-market fills at stop ± slippage (or at a gapping open beyond the trigger);`);
  lines.push(`  stop-limit gap-misses survive (honest).`);
  lines.push(`- Stop-outs do NOT halt the run: each models an operator redeploy (documented restart model).`);
  lines.push(`- Sanity gates (throw on violation): stops never fire EARLY (at/above −stopLossPct required);`);
  lines.push(`  crossed-but-unfilled resting stops throw (sim mismatch tripwire); every TP cycle net > 0.`);
  lines.push(`- Liquidations table (wick ruin past −100% ROI):`);
  if (report.liquidationEvents.length === 0) {
    lines.push(`  none.`);
  } else {
    for (const e of report.liquidationEvents) {
      lines.push(
        `  - candle #${e.index} @ ${new Date(e.timestamp).toISOString()}: ${fmt(e.roiAtExtremePct)}% (${e.hadStop ? "gap through a resting stop" : "naked — no Layer-1 stop (sub-min sizing?)"}).`,
      );
    }
  }
  if (report.openPosition) {
    const p = report.openPosition;
    lines.push(
      `- Open position at end-of-data (marked to close, excluded from win rate): ${p.direction} ${p.totalQty} @ avg ${p.avgEntry} (${fmt(p.unrealizedPct)}% unrealized).`,
    );
  } else {
    lines.push(`- No open position at end-of-data.`);
  }
  lines.push(``);
  return lines.join("\n");
}
